#!/usr/bin/env python3
"""SudachiDict lex CSV から「漢字を含む普通名詞」を抽出して corpus 形式で出力する。

## 経緯

akaza-data の make-dict は SudachiDict から:
- 名詞-固有名詞-一般
- 名詞-普通名詞 (表層形が**全カタカナ**のみ)

しか拾わない (= make_sudachi_dict のフィルタ)。
そのため「既読 / 既得 / 危篤」のような **普通の漢字熟語が dict に入らない** という
症状を 2026-06-08 のユーザー実機テストで観測。

本スクリプトは SudachiDict CSV から **名詞-普通名詞 で表層形に漢字を含むもの** を
抽出して corpus 形式 (`surface/yomi` を space 区切り) で出力する。
make-dict の `--corpus` 引数は **make_corpus_dict 経由でフィルタなく全 word を
dict に追加する** ため、上流 akaza-data に手を入れずに同じ効果が得られる。

## SudachiDict CSV フォーマット

カンマ区切り 18 列 (csv[0]..csv[17]):
- csv[0]: 見出し形 (= 表層形)
- csv[5]: 品詞大分類 (例: 名詞)
- csv[6]: 品詞中分類 (例: 普通名詞)
- csv[7]: 品詞小分類
- csv[11]: 読み (カタカナ)
- csv[12]: 表記形

## 出力フォーマット

1 行 1 単語の corpus:

```
既読/きどく
既得/きとく
...
```

libakaza の corpus parser は space 区切りで `surface/yomi` を解釈するため、
1 単語 1 行で問題ない (BOS/EOS マーカは内部で trim される)。
"""

import csv
import sys
from pathlib import Path


# 拾う品詞 (= make_sudachi_dict の名詞-普通名詞拡張版)
# 「カタカナのみ」フィルタを外して、漢字を含む普通名詞も拾う
TARGET_POS1 = {"名詞"}
TARGET_POS2 = {"普通名詞"}

# 全角空白を含むエントリはスキップ (make_sudachi_dict と同じ)
ZENKAKU_SPACE = "　"

# ひらがな範囲
HIRAGANA_START = 0x3041
HIRAGANA_END = 0x3094

# カタカナ範囲
KATAKANA_START = 0x30A1
KATAKANA_END = 0x30F6


def katakana_to_hiragana(s: str) -> str:
    """カタカナ → ひらがな変換。長音記号「ー」等はそのまま残す。"""
    out_chars = []
    for ch in s:
        cp = ord(ch)
        if KATAKANA_START <= cp <= KATAKANA_END:
            out_chars.append(chr(cp - 0x60))
        else:
            out_chars.append(ch)
    return "".join(out_chars)


def has_kanji(s: str) -> bool:
    """文字列に漢字 (CJK Unified Ideographs) が含まれるか判定。"""
    for ch in s:
        cp = ord(ch)
        # CJK Unified Ideographs + CJK Extension A
        if (0x4E00 <= cp <= 0x9FFF) or (0x3400 <= cp <= 0x4DBF):
            return True
    return False


def is_hiragana_start(s: str) -> bool:
    """文字列の先頭が通常のひらがな (ぁ〜ゔ) か。"""
    if not s:
        return False
    cp = ord(s[0])
    return HIRAGANA_START <= cp <= HIRAGANA_END


def extract_entries(csv_path: Path, dedupe: set) -> list:
    """1 つの lex CSV から対象エントリを抽出。重複は dedupe で除去。"""
    entries = []
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        # SudachiDict CSV は QUOTE_NONE (普通の CSV) で問題ない想定
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 13:
                continue

            surface = row[0]
            pos1 = row[5]
            pos2 = row[6]
            yomi_kata = row[11]

            if pos1 not in TARGET_POS1:
                continue
            if pos2 not in TARGET_POS2:
                continue
            if not has_kanji(surface):
                continue  # 全カタカナ語は make_sudachi_dict が既に拾う
            if ZENKAKU_SPACE in surface or ZENKAKU_SPACE in yomi_kata:
                continue
            if not yomi_kata or not surface:
                continue

            yomi = katakana_to_hiragana(yomi_kata)
            if not is_hiragana_start(yomi):
                continue
            # surface に space が含まれると corpus フォーマットが壊れるのでスキップ
            if " " in surface or " " in yomi:
                continue
            # 「/」も区切り文字としてフォーマットを壊すのでスキップ
            if "/" in surface or "/" in yomi:
                continue

            key = (yomi, surface)
            if key in dedupe:
                continue
            dedupe.add(key)
            entries.append((surface, yomi))
    return entries


def main():
    if len(sys.argv) < 3:
        print(
            "usage: sudachi_to_corpus.py <out_corpus_path> <lex_csv> [<lex_csv> ...]",
            file=sys.stderr,
        )
        sys.exit(2)

    out_path = Path(sys.argv[1])
    lex_paths = [Path(p) for p in sys.argv[2:]]

    dedupe = set()
    all_entries = []
    for lex in lex_paths:
        if not lex.exists():
            print(f"warning: lex file not found: {lex}", file=sys.stderr)
            continue
        es = extract_entries(lex, dedupe)
        all_entries.extend(es)
        print(f"  {lex.name}: {len(es)} new entries", file=sys.stderr)

    print(f"total: {len(all_entries)} entries", file=sys.stderr)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write(";; nuko-ime SudachiDict 漢字普通名詞 corpus\n")
        f.write(";; Generated by scripts/sudachi_to_corpus.py\n")
        f.write(f";; total entries: {len(all_entries)}\n")
        for surface, yomi in all_entries:
            f.write(f"{surface}/{yomi}\n")
    print(f"wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
